language: node_js
sudo: false
node_js:
- '6'
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAJJIVPVVET2LD2OQA
  secret_access_key:
    secure: mO+g6s9U/aGX4iqJteu+9IZr1jW/tJQl/RVn/79+FL7ROeayCyn/NNm2njLFg7ZZSZLaAESj1OMBFDzbKCyPye6dv/crtozNlbEpu9o2m1FXuXzQINPfhkujgm9SKlOLhhCiY/3xhN0SY5PEMui3p2HK6UgNpox16xi8ULIz5UXlh9z6RVatg7Fub8elwz1BL4aBT9djYsdjbsAK0WyLFhdkXhqIXSKQF7GWufwNTJrNJy95H868t1FIaHWUfW9ob3++yP7yPjAAcI9TxDTBM4TP2lUgGRAGhealVMfucoZSTmGBDPR/v/hh0D0Tp4jkAioyEp5UFcF9J6ZB24/cHZehJxetQWAabQu4BAbnBCdJxAkDX8qb3SooM6XO9BS+cvVf55mHgou2pZ4bkvm7hVtY516OsQq7jgLAaaF7mBzVpwG/6JAJDP7EK62KesdDFGSZH0USKRSqk4rkcpnxUgIEhkKcceUuUhubpeiyLVsiH6d6uMOGnqXt6TLjndMULADj5s3gjphdoWdau++5J8j4TJveYAlH39crNTwJtd1qqGMAoWPObo8hpmFleT30wzFGQVYB+CmtR3+/7AB8aoWXZnUG0yecLizefHcGd6+p/9QHoxIal7IbLy9SRjUzk+kl3VM6O6Nwv4OgX0WvjiV3TX/nGrDwNuyU81Ih39c=
  bucket: bucketeer-43061060-5d3e-4179-9d24-f43a1f2b1cbf
  local-dir: assets
  acl: public_read
  on:
    repo: nci-ats/hhs-oig-web-asp
    all_branches: true
