
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<head>
<meta name="google-site-verification" content="tpATPqNEN3HXiSbtqevBE9NdgbuCiN9Vmr6EP94lx6w" />
<meta name="keywords" content="Video | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services" />
<meta name="description" content="Podcasts | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services" />
<title>Podcasts | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services</title>
<!--#include virtual="/layout/head.asp" -->



<!-------------/ head closes and body opens / --->

<!--#include virtual="/layout/head-body-tags.asp" -->

<!------------/ head closes and body opens / --->


<div id="bodyContainer">
	<div id="textReset">
	<!--#include virtual="/layout/header.asp" -->
			<div id="mainBody">
			<div id="leftSideInterior">
				<div id="breadcrumbs">
					<ul>
						<li>
							<a href="/">Home</a>
						</li>
						<li>
							<a href="/newsroom/index.asp">Newsroom</a>
						</li>
					
						<li>
						<a href="/newsroom/podcasts/">Podcasts</a>
						</li>
            
						<li>
						Transcript
						</li>            
            
					</ul>
				</div>
				<div id="leftContentInterior">
					<h1>Transcript for audio podcast:  2012 Health Care Compliance Association Compliance Institute Keynote Address</h1>
					<!--<div class="featuredContent">
						<div class="archiveYears">
						 Jump to: <a href="#may">May </a>, <a href="#april">April</a>

						
						</div>
						<a class="top r" href="#top">Top</a>
						<div class="clear"></div>

					</div>-->

<p>From the Office of Inspector General of Department of Health and Human Services</p>

<p><a href="http://www.oig.hhs.gov">http://www.oig.hhs.gov</a></p>

<p>Daniel Levinson: It's great to be back with you. And a lot has happened over the past year, including a survey that was done by HCCA that I read about, over the winter, in Modern Healthcare Magazine, that revealed that six out of 10 compliance officers lose sleep over their job [laughter], such that it impairs their performance. And about the same number actually have contemplated leaving the profession over it. And that really got my attention. Roy was quoted in the Modern Healthcare piece as saying that it's a national crisis, and I understand what he's talking about. As I thought about it, it occurred to me that it's actually a good idea to give bad people stress, in this field. But it's a bad idea to give good people stress, in this field. And I've been around for a few years with you, as some of you know, and I think I know my audience. And you are the good guys. [Laughter, applause, cheers] It's actually true. </p>
<p>So, behind my desk, I was thinking, well, what do I need to do, if I'm concerned about it? One is I could sit behind my desk and worry about it, drive my own stress up. But then I really wouldn't be following the advice I want to give you this morning, and that is to try to do something about it, in a positive way; to try to learn what's behind the stress and take -- take action. The way I typically take action, when I get frustrated, when I get stressed, is to try to learn more about why I feel stressed. And there's a lot, especially in our field. So I figured, well, one of the best ways is to get a more specific idea of what's on your mind. Now, generally, the things that are on my mind I know are on your mind, and vice versa. But it would be helpful to actually get a more comprehensive idea. </p>
<p>So we asked, a couple of months ago -- HCCA -- if we could partner in -- in having you ask questions. That was behind the Ask the IG idea, at least in part, was for me to get better idea of what's going on in your life. And you were great. Thank you so much for the responses that I got. It was really terrific to get questions from many of you. And I went to some effort to actually write down the questions on cards, and I've got a number of the cards with me this morning. And before I raise the stress level, there are no names on these cards [laughter]. No names. These are just -- these are questions. I spread the questions out on the table, because I also wanted to draw, you know, some general lessons of what's going on in the field. And it was interesting. It really occurred to me that it would be helpful to understand just how big a field that we play on. </p>
<p>You know, healthcare, in the United States, is -- as you know -- huge. It's the largest service industry in the United States. If the entire economy of the country is something like $15 trillion, health care alone accounts for somewhere between two and a half and $3 trillion. We operate in a vast -- in a very large field. And we operate in a field that's flawed. I mean, there are -- there are problems. It is not a culture of corruption. We have so many fine healthcare professionals across the entire spectrum of health care. There's a lot to be proud of. There's a lot to admire about healthcare in the United States. It's huge. We spend a lot of money. We have a lot of rules. But we also know that we have a considerable number of problems. And healthcare experts across a wide spectrum of expertise, if you will, estimate that anywhere from 20 to 30% of what we spend in healthcare is waste. And you'll notice that what I've done is incorporate fraud into that waste circle, because a certain amount of waste is fraud. All fraud, as far as I'm concerned, is waste, but not all waste is fraud. And sometimes -- many times -- it can be difficult to determine which is which. And it's important to distinguish, given how serious fraud is, and certainly from a legal perspective, and from other perspectives, as well. I never throw out a figure about how much fraud there is, but we know there's fraud. And that is serious, both financially and in terms of patient safety. For many reasons that's especially serious. But 20 to 30% of expenditures in waste, fraud, and abuse is something that gives one pause about -- about how -- how large the challenge is, to get -- to get healthcare right. </p>
<p>We operate not only in a very vast area, but we operate in an area that's extremely complex. And I'm not talking just about the complexity that you face within your own organizations. And I know that many companies have -- have very, very complicated arrangements. There's a lot of human relations that, of course, it's true across industries, but -- but especially in healthcare, which brings together so many different, important professions, occupations. It's especially challenging, I think, in the workplace. But outside of your operations, as well, there are a number of different authorities. And it -- it really brought home to me how confusing it can be to have to deal with, with all of these different authorities, because there were -- there were a number of questions that were posed about mandatory compliance plan rules, and ACO program requirements, and E&M coding requirements. </p>
<p>You were asking good questions. But actually, there were questions that -- that most appropriately would be directed elsewhere. CMS still is the part of government that is running programs. The OIG has an important role, which we'll certainly get to. But it's -- it's important to keep in mind the central role that CMS plays in program administration. </p>
<p>And a number of the questions really were -- they were good questions, but they needed to be directed, ultimately, at some of our government partners. And it would -- it's helpful to keep focused, when it comes to OIG, on the oversight and enforcement role. By the way, a certain number of questions just had to do with what we should do internally that should trigger, really, conversation with Counsel's office. And the relationship, I know, between compliance and the counsel's office can be complicated, as well. My view on that, I feel compelled to share, is that it really is helpful to have compliance functions separated from counsel functions. I know that if I'm a board member of a healthcare provider, I think it would be helpful to be able to go to my CLO -- my chief legal officer -- and say, is it defensible? Is what we're doing pass muster, in case it's legally challenged. I also want to go to my CCO -- my chief compliance officer -- and say, is it right? In most instances, I think the answer is going to be the same. Hopefully, it will be the same. It would be great if it was always the same, but I don't have that confidence. And if I'm uncertain about whether the answer is the same, I would much prefer to hear about it in-house than to read about it on the front page of the New York Times or the Wall Street Journal. I like the idea of having separate channels from the legal office to the board, from the compliance office to the board. </p>
<p>In terms of how OIG fits in to the various authorities that you have to deal with, I kind of view OIG in terms of the -- my 5-letter acronym, which some of you veterans in the audience have heard me talk about before. And I promise I will not be throwing a lot of acronyms at you this morning. I have, really, only two. But one is EPCOR. And I think EPCOR kind of wraps up around what is our health core -- what is our healthcare building this morning. EPCOR kind of wraps around all of the chief functions, really, that OIG is concerned about. It stands -- the E stands for enrollment. The P stands for payment. C stands for compliance. The O stands for oversight. And the R stands for remediation. </p>
<p>Let's go with enrollment. You actually weren't asking questions about who gets to enroll in our programs. That's really the government's business. And as you know, the government has had a real challenge handling enrollment effectively over the years. Given the historical nature of our programs, and the idea that any willing provider could enter Medicare, unfortunately we've had people come in the in door -- you can think of enrollment as entrance or gatekeeping. A number of folks come in the -- in the healthcare building that had no business being in the healthcare building, that were taking advantage of some of that $2.7 trillion or so that exists. And that includes both public and private. Government needs to do a better job, by making sure that only the right people -- people who are genuinely focused on providing necessary health care services -- actually get into the building in the first place. It's really helpful to know that the enrollment challenge is headed in the right direction. CMS is engaged in a lot of important initiatives on provider screening that looks to be far more effective, hopefully, in the future, in keeping the wrong people out and making sure that if you get a provider number, your -- you're the kind of provider that we want in Medicare. As I say, some people really don't belong in the building at all. </p>
<p>Unfortunately, there are some who have the qualifications, who are appropriately admitted, and then things go bad. That's when bad things happen to good institutions, and we'll talk about that, as well. </p>
<p>Let's go to P, to payment. And of course, that's what, at core, we're really about. And payment can really induce a certain amount of stress, because there are just so many issues that we need to deal with -- not just on the private side, but on the government side, too. We're always concerned about whether the government is receiving the rebates and the reimbursements that it deserves; whether we're getting value for durable medical equipment; whether we're getting the right kind of pricing; whether we're really keeping up-to-date with market conditions; whether we're overpaying. I know we're focused on overpayments, and there have been a number of questions that have been posed about that. What do we do, if we find in improper payment, such as the use of a CPT code that was misunderstood and resulted in an erroneous claim? A good question. Pay it back. Pay it back sooner rather than later. Overpayments have been a serious problem for many, many years. CMS is involved, as you know, systemically, in trying to address it. The Affordable Care Act provides additional tools for that. And as a general matter for Inspector Generals around government, IGs are constantly concerned about the high level of erroneous payments that are being made. This is true across programs, but in healthcare it's especially serious. And the problem with erroneous payments is, you know, we just don't know whether we're paying the right dollar for the right service. So, we -- we really can't say whether it was just an innocent mistake or whether there's something more serious. Undoubtedly, the very disturbingly high improper payment rate is -- is, to a certain degree, fraud. But it isn't all fraud. A lot of it is mistake. And some of the best -- some of the cleverest frauds would never show up in the erroneous payment channel at all, you know. The fraudsters have done it exactly right. So it's not a substitute for coming up with a -- with a fraud strategy. So, we have -- we have concerns. We're not stressed about it. What we're trying to do is learn more about the sources of payment problems and try to attack them, you know, really effectively. We try to do it in government. You need robust systems to remedy quickly overpayments in your operations. </p>
<p>Let's go to the -- to the corner of our healthcare building, and we've put the C -- compliance -- as our cornerstone, because that's what we're all about. And what I want to share with you here is that we got a number of questions about ACOs, which, rather than use that expression, I would prefer to talk about coordinated care. And what I want to share with you is that -- is that I think that we're -- and this could be a -- a cause for stress, I understand. It certainly is a cause for really highly-focused interest. I think we're in the midst of what I would call a -- what seems to be a paradigm shift. I think the -- the various initiatives that are being undertaken now by CMS -- the kind of initiatives that actually we've seen before, both in government and especially in the private sector, over the last five to 10 years -- I think is all part of a trend, which I would call the move, really, from fragmented care, from piecemeal -- if you will -- service, to healthcare professionals working across professional lines, in a more coordinated fashion. I think we're moving from fragmented to coordinated care. I think we're moving, in healthcare, from what I would call volume-based payment to value-based payment; rather than pay per particular service, to be paying for whether it -- in fact, you have achieved your healthcare objectives: Better health for the patient. </p>
<p>This is not an easy thing to encompass, because you're talking about significant, systemic change. You've got to figure out, you know, how you're getting paid, who you're getting paid by, how you're accounting for it. There are a lot of metrics involved, and you've heard about many of those metrics that are part of some of the CMS initiatives. And it -- I can well understand that it's a -- it's a cause for, you know, some potential stress. But a lot of it is going to be unfolding over the next few years. We're also talking about a present challenge having to do with the realization of what healthcare will look like in the future. And the fact of the matter is, there's a lot about the future that we don't know. We don't know, for example, what the Supreme Court is going to decide, in its decisions in the future. We don't know what the election results are going to be in the future. And we don't necessarily know exactly how a lot of the coordinated care models will solidify in the future. Hopefully, we're all headed to the future, and we will find out over time. But there's enough activity that's going on, in the world of coordinated care, for us to focus on it, to understand it as best we can, to reach out to those who are designing these systems, and to be asking the questions. </p>
<p>It really is a paradigm shift. Paradigm shifts happen in healthcare. Maybe not often, but they do. And I think my favorite example of a paradigm shift is there are some -- there are some famous paintings of surgeons in the late 19th century, in America. And these paintings show the surgeons, with the patient laid out on the table, surrounded by medical students. And the surgeons are wearing business suits, with white shirts and black ties. Their hands are covered in blood -- their bare hands. And they're looking proudly out at the viewer, confident that they are delivering world-class medicine. Yes, they've heard that over in Europe there's some obsession with anti-sepsis. The Europeans are wimps [laughter]. We're Americans. We get the job done. You can -- you can see it in their eyes. And believe me, every fiber of their being believes that they are helping the patient. They don't believe they are harming the patient at all. And unfortunately, as we know, they are wrong. And in many cases, they are dead wrong. And we -- we learned that. And that's one of the great advances of the 20th century. But come back with me to the -- I don't -- to the 1890s. And let's -- let's think about what our predecessors had to be thinking, at the time of the paradigm shift. So let me -- let me get this clear. You want me to make sure that the theater of operation is completely absent of something I can't see, I can't hear, I can't smell, and I can't touch. You've got to be kidding. That was the state of science. That was the state of technology. And that was by and large conquered, over the course of a number of years. These days, we're supposed to do things a lot faster. And I do think that's -- to a certain degree -- stress-inducing. Things have to happen with greater rapidity. The stakes just seem to be higher. Actually, the stakes were pretty high back then, too, especially if you were the one on the table. But now, we have to deal with -- with big data, with technology that -- that seems to be really quite awesome, from wherever we sit or stand in healthcare.</p>
<p>And especially for those of us of a certain age, you know, it's -- it's complicated. But rather than it be a source of stress, I think it needs to be a source of -- and I went back to that -- that story of the 19th century, because I -- to a certain degree, it's inspiring, I think, to know that, you know, we can go from -- from total -- total absence of awareness about our environment to such keen awareness of our environment, such that we can create a much more effective environment for positive healthcare results. Some of those stories of the past I think can serve as -- as ways of looking towards the future in a more positive way. I think this is something that's -- that's unfolding, as we're here and will continue to do so in the next few years. I know from my part I'm trying to understand and ask the questions from an OIG perspective. I encourage you to be doing the same from yours. </p>
<p>Let's move to oversight. And on oversight, we -- we got a number of questions. Is there an update on the findings of the hospital compliance audits? What are the greatest risks and errors for the average hospital? I understand that there's great interest in the national hospital audits that OIG is doing. And there, you know, I just think it's helpful to always keep in mind the risk areas that traditionally have been of concern. You know, everything from, you know, getting claims for short stays, right, to credits for medical devices, and everything in between. There are about 20 or so audit reports that have been posted on our website, over the course of the last few months. There are about 70 audits or so that are in process. I think it's really a great example of advances in information technology that we're able to now look at a collection of potential risk areas, be able to do audits in a more comprehensive way. It's a far more efficient way of being able to look at claims data, the kind of thing that, actually, a few years ago I don't think would've been possible. That's really a very positive use of being able to use data. And when it comes to oversight, we need to think both in terms of the very positive things we can do, as a result of new data tools, of analytics, of be able -- being able to get data in real time -- or almost real time. And we also need -- in terms of oversight -- to be able to be aware, at all times, of the potential negative impact of information technology, in the hands of those who would do harm to the system. Because there's everything from privacy concerns to bio-terrorism concerns. I mean, technology is great, but it's neutral. Like every other great new technology, it can be used for very important and valuable social purposes. It can also be used to do terrific harm. So, you know, we need to enter our world of better technology and big data very, very sensitive to both the good it can do and the evil it can also manage to do to our systems. Very important to keep our healthcare building as clean as possible, on that score. </p>
<p>Let me go to remediation. As you can see, that's the out door. That has to do with our law enforcement responsibilities. And this is the second -- and I promise -- last acronym I'll be throwing at you. But I think it's actually kind of a useful way to keep in mind the enforcement authorities that we use, because I can well understand that enforcement authorities might be a source of stress [laughter]. And again, I think the more you -- you feel comfortable knowing about these enforcement authorities, I think the less stress they bring. And when it comes to remediation, the questions I got were, you know, what role do agents play in strike force? It might be helpful to understand that they play a lot of different roles. </p>
<p>But let me give you the acronym for the enforcement authorities. It's the False Claims Act, the Anti-Kickback Statute, the Civil Monetary Penalties Law, the Exclusion Statute, and the Stark law. I call it the five FACES of OIG law enforcement. So, if you can keep in mind FACES, I don't think you'll have any trouble, then, at least remembering. This isn't the entire scope of the authorities that we use, but it'll be a relatively easy way to recall that we're dealing with the False Claims Act, the Anti-Kickback Statute, Civil Monetary Penalties Law, Exclusion Statute, and Stark Law -- which as the veterans know is the Physician Self-Referral Law. On remediation, there was -- I just wanted these up, so that you can kind of keep that in mind. </p>
<p>There was a question about what our agents are doing in strike forces. I think -- I think our work in strike forces -- which I'm sure you've heard about, you've read about -- we're actually very proud about the results, because billions of dollars have been returned to the Treasury, as a result of the strategic partnership that has been put together over the last several years, really lead, at the very top level, by the Attorney General and our secretary, to focus on concentrated scams, frauds in many of the major cities of the country -- everywhere from Miami and New York to Houston, Dallas, Detroit, Chicago, Los Angeles -- and really do a more focused effort on keeping the wrong people from getting into the healthcare building in the first place; to do a better job of making sure that our healthcare building remains clean. And, as I say, billions of dollars have been brought back. What agents have been doing is very important on the groundwork -- the usual work that you'd expect law enforcement personnel to do, based on tips, based on understanding the data and being able to be technologically savvy about what the data is showing, in terms of whether we have billing patterns that are clinically incoherent or not, and then putting those pieces together. They've been bringing back money. They've been protecting patients. And they've been -- they've been risking their lives. I mean, in some of these strike force cases, you know, we're dealing with organized crime at times. And caches of weapons have been uncovered, in the course of investigations. I'm proud of our agents for a number of reasons, not the least of which is they really put themselves very often in harm's way, to make sure that -- as I say -- the wrong people don't get into our system in the first place. So if there's any potential stress reduction, when it comes to strike force, I feel better about the job the government is doing to keep our system cleaner. </p>
<p>And I'm pleased to share with you that we're doing better for our taxpayers, and I think for the healthcare community generally, to make sure that the criminal element doesn't get into the system, if possible; and when it does, that it gets shut down very, very quickly. We bring back $7 for every dollar that is invested in OIG, because of these multibillion-dollar recoveries -- something that we're very proud of. I want to share with you -- since we last met, about a year ago, we have been doing great work, I think, in our ability to communicate with you on the Web. And always keep our address handy. It's on the screen now. And we have an amazing collection of resources, I think, that you'll find invaluable. We have our Avoiding Medicare and Medicaid Fraud and Abuse, our roadmap for new physicians. It isn't just for new physicians. I think that you'll find this particular product valuable, no matter who you are and -- or where you are. It has, actually, a very good layman-like explanation, in a couple of pages, of FACES -- the five law enforcement authorities I just talked about. Within two or three pages, you can get a very good understanding of what those laws are about. Our compliance educational materials have been updated and provide a wealth of information. I hope that you've had opportunities to catch our videos, our -- of course, our compliance program guidance. </p>
<p>You know, the guidance like the -- for hospitals, for nursing homes, for the pharmaceutical industry. Those what we call CPGs have been on our website for a number of years, but many of these have been updated and provide a wealth of information. There's scores of advisory opinions that have been issued by our counsel's office, on our website. I would encourage you. It's a stress reducer. In fact, if you're having trouble going to sleep, you can take a few home [laughter] and just -- if you start to read them, that might help [laughter]. But -- but indeed, if -- if you really are concerned on a particular subject, and you find that there's one or more advisory opinions that are on the Web, it would really be wise to invest the time and understand it. </p>
<p>We have our 1-800-HHS-TIPS line. And indeed, a lot of the work our agents do, a lot of the most important cases that have been worked by our office, have come about as a result of people from all walks of life -- whether it's beneficiaries, whether it's company managers and executives -- using our tips line, to inform us of very, very important fraud scams that need to be closed down. Our OIG listservs, I encourage all of you to subscribe. We have thousands of people who have been getting on our listserv recently, and they are getting updates -- daily updates -- on what's going on with OIG. And obviously, it affects your lives every day. So it's a good idea to be aware of our OIG listserv, to get on it, to subscribe. </p>
<p>One of the additional vehicles that we have on our Web are -- is the special advisory bulletins that we sometimes issue. And on this, I do want to note that we got a number of questions from you on exclusions. Exclusions, you remember, is the E in FACES. And there's been important developments on exclusions, on making sure that the people who have gotten into the healthcare building, not only when they get out stay out, for as long as they're supposed to stay out; but they don't act as if they're in the building. You don't want to honor bills from those who have been excluded. So it's important to keep abreast of developments, with respect to exclusions. We did do a special advisory bulletin over a decade ago about the consequences of exclusion. </p>
<p>And listening to the concerns that the community have had about the importance of getting exclusion practice right -- you know, how often should you check the LEIE -- that's not my acronym. That's one that's been around for a while -- the List of Excluded Individuals and Entities. We -- we are working on a revision, on a supplement, if you will, to the advice that's already out there. So, by all means, keep -- keep aware of what's coming down the pike. We will be issuing a special advisory bulletin on exclusions. One of the most important questions that you posed is how often should we be checking the LEIE. And I can tell you that our practice is to update the list monthly. So, you know, without trying to put the cat out of the bag here, I don't think it would be a bad idea if you check the LEIE monthly. </p>
<p>Follow us at OIG at HHS. We are social media savvy. I'm not [laughter], but we are -- the royal we are. We are on Twitter. Check out YouTube. We do podcasts. And some of you have been very generous in your praise, this week, at telling me how much you value the podcasts. We have quite a few of them. We have some -- we have some rock stars of healthcare compliance, I think, in our office. And they have been very generous with their time and talent. They have developed webcasts, podcasts. They're on the Web, and they are worth listening to. I think they are just terrific. I think you'll find them not just entertaining, but you'll find them informative. It's -- it's worth your time. And of course, e-mail us, you know. These are -- these are all valuable social media tools, and I would encourage you to use them. </p>
<p>Again, I want to thank you for the questions that you posed. I took them very, very seriously. I think they provided some insight to me about, you know, what are -- what are some of the stress areas for you. And I want you to know that I'm going to -- I'm going to keep these questions with me. Again, there are no names on these cards [laughter]. I'm going to -- I'm going to keep these questions. And the way I viewed it, I view it as really it's the beginning of a conversation that we should certainly continue. And what I want to see happen is for you to be deputized as corporate IGs [laughter]. I -- what I want to see is for you to get the resources that you need. I want to see you get the respect that you deserve. I want to make sure that you are successful, because your company is counting on you to be successful. And in a real sense, the country is counting on you to be successful. This is important work that you're doing, and we need to do it together. To the extent that we can, we're here to help. I want to continue this conversation. I want us to lose the stress. And I want to focus on getting the job done. I think we have the right talent in the room to get the job done. And I'm wishing you every success. We're here to help you, and we'll stay with it. And with that, thank you for your attention. Let's have a terrific conference this week. Thank you. [Applause]</p>


<div class="contentSeparator"></div>

		
<p><p><a class="top" href="#top">Top</a></p></p>
<p><a class="back" href="/newsroom/podcasts/">Return to Podcasts</a></p>
					
				</div><!-- leftContentInterior ends -->
			</div>	<!-- leftSideInterior ends -->
			<div id="rightSide">
				<!--#include virtual="/layout/im-looking-for.asp" -->
				<!-- #include virtual="/layout/sub-navigation/subnavigation-media.asp" -->
				<!--#include virtual="/layout/exclusions-database.asp" -->
				<!--#include virtual="/layout/report-fraud.asp" -->
				<div class="clearPadding"></div>
				<!--#include virtual="/layout/email-alerts.asp" -->
			</div><!-- rightSide ends -->
			<div class="clear"></div>
		</div><!-- mainBody ends -->
	</div><!-- textReset ends -->
</div><!-- bodyContainer ends -->
<div id="footerContainer">
	<!--#include virtual="/layout/footer-top.asp" -->
</div><!-- footerContainer ends -->
<div id="footerBottomContainer">
	<!-- #include virtual="/layout/footer-bottom.asp" -->
</div><!-- footerBottomContainer -->
</body>
</html>
