
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<head>
<meta name="google-site-verification" content="tpATPqNEN3HXiSbtqevBE9NdgbuCiN9Vmr6EP94lx6w" />
<meta name="keywords" content="Video | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services" />
<meta name="description" content="Podcasts | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services" />
<title>Podcasts | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services</title>
<!--#include virtual="/layout/head.asp" -->



<!-------------/ head closes and body opens / --->

<!--#include virtual="/layout/head-body-tags.asp" -->

<!------------/ head closes and body opens / --->


<div id="bodyContainer">
	<div id="textReset">
	<!--#include virtual="/layout/header.asp" -->
			<div id="mainBody">
			<div id="leftSideInterior">
				<div id="breadcrumbs">
					<ul>
						<li>
							<a href="/">Home</a>
						</li>
						<li>
							<a href="/newsroom/index.asp">Newsroom</a>
						</li>
					
						<li>
						<a href="/newsroom/podcasts/">Podcasts</a>
						</li>
            
						<li>
						Transcript
						</li>            
            
					</ul>
				</div>
				<div id="leftContentInterior">
					<h1>Transcript for audio podcast: 2014 Health Care Compliance Association Compliance Institute Keynote Address</h1>

<p>From the Office of Inspector General of Department of Health and Human Services</p>

<p><a href="http://oig.hhs.gov">http://oig.hhs.gov</a></p>


<p>Thank you so much. Thank you so much. It is so wonderful to be back again with HCCA. As I was approaching this event, I was starting to think, "Why do I get so excited? Why do I so much look forward to being with you all at this annual event?" I started talking to myself. And it occurred to me that I don't really look forward to sharing a lot of data points with you. I'm not really here to discuss and bring back lots of data, as big as data is these days. What I have concluded is that what really excites me is about the opportunity to actually talk with you in person. This is the only time during the course of a typical year when we're not communicating through the internet or through technology that we can actually meet in person. </p>
<p>This particular event, of course, is counting on technology for me to communicate with a lot of people at one time, and as valuable as I find it, I also look forward even more to the chance to actually see you at the networking sessions, over a meal, in the hallways. And data, as important as it is -- and these days technology is so powerful. We know that technology can do things like assemble information that we mere mortals can't do in terms of the magnitude and retrieve it the way that we can't. But there are things that technology lacks that I find is in abundance when I come here. What I find here is good judgment. What I find here is keen insight. And what I find here is real passion, passion for healthcare compliance, for doing the job really, really well. I don't get that from technology. Now, up the coast from where we are, there's a place in the country called Silicon Valley. And that's really where the center is for the folks over the last couple of decades to develop tremendous technology. So when I think of the Bay Area, when I think of San Francisco and the tremendous number of important companies that have created new industry, I think that's really where the center of technology is. When I think of San Diego, I tend not to think about technology. I tend to think about biology. If at some point during the week you can somehow manage to get to the world-famous San Diego Zoo, the Safari Park, SeaWorld, you'll come to appreciate that we carbon-based creatures actually have a lot to offer. We're interesting, we're fun. </p>
<p>I put a tree frog on our first slide as kind of a symbol of carbon-based creatures. And we're carbon-based creatures. And we do bring special insights to what we do. And for thousands of years, actually, we humans have looked to various animals and so forth for representations of courage and of strength. And when I think about it, I think it's a good idea to kind of use these carbon-based creatures over the course of the next few minutes to talk about our update, what we're doing at OIG. And this tree frog looks like it's especially interested in learning what's going on today, right now. What is urgent? What is happening as we speak? Well, it's March 31. So for many Americans, this is the last day to sign up for the market insurance, for the health insurance marketplaces. The health insurance marketplaces got off to, as we know, a rocky start. And both the department and the Congress have asked OIG to look at the health insurance marketplaces, understand where the problems occurred as it unrolled and as it rolled out in a flawed way, and to take a measure of where things are now to get a better sense of where issues need to be addressed as we go forward. </p>
<p>So what is OIG looking at? We're looking at payment accuracy -- there are a lot of payments to be made to insurers -- tax credits, cost sharing, premium stabilization payments. Many aspects of payment accuracy need to be explored, which we're doing now. We're looking at eligibility, who is eligible to sign up. So we're looking at the internal controls. And, again, there are cost sharing provisions and tax credits involved. We're looking at contracts and the contractors that were involved in establishing the marketplaces. So we're looking at contract planning, contract acquisition, contract management, contract performance. And, of course, we're looking at security, cybersecurity threats potentially and fraud against consumers. It is a very huge portfolio of work. We're involved with it now and we have quick timetables for the balance of the year to complete our work. But this is of great urgency, I think, to the country and the Congress and the department need a better understanding if these marketplaces are going to work, about how to ensure that, going forward, the kinds of problems that were experienced as we came up to 2014 and the early time of 2014, is not repeated. </p>
<p>Thought leaders. One wouldn't ordinarily think of an octopus as a thought leader. But, indeed, it turns out that the octopus actually has a great mind. I didn't put up the octopus because it's got lots of hands and I know that you've got lots of different things that you need to worry about at one time and you're multi-tasking all the time. I think the octopus is important because it uses all of its hands to solve a particular problem. And scientists have been able to document that if you give an octopus a jar, closed jar, with some food in it, that the octopus will manipulate the jar in a variety of ways to try to understand how best to get at the food, that it's truly a thinking creature. And that comes to mind in terms of the kinds of big issues that we have and that we need to navigate through. I mean, for us, as I mentioned, it's the marketplaces that we're currently involved with. I know on your minds are big-picture issues like, you know, what's going to happen with the SGR, which is probably being talked about in Washington as we speak here; what's happening with ICD-10, with the second stage of the meaningful use. </p>
<p>Big-picture issues. When it comes to understanding a larger landscape, I so much encourage you to take advantage of our work plan which was issued at the beginning of the year and especially focusing on, for this audience, the hospital compliance reviews. And we're looking at a variety of very important issues. I think they can be kind of divided up into billings and payments across a wide range of inpatient and outpatient services. They can be considered in terms of policies and procedures as we look at the kinds of billings that are made in light of new Medicaid rules. And, of course, quality inpatient safety has become a very important priority for us, and I know it's an important priority for you. And we have looked at adverse events issues as they have occurred in hospitals. We have looked at adverse event issues in nursing facilities. And we're now undertaking important work in inpatient rehab facilities, as well, to examine adverse events. All of them big-picture issues, worthwhile to really drill down on our work plan for the year because you'll find a lot of detail. You'll be able to really navigate how we view the landscape going forward. And I do think that the work will be valuable to you. </p>
<p>This, I think, is the most beautiful slide of the morning. Parrots are beautiful to look at. Their problem is that they only will say what they hear. And parroting is a potential risk in our field, the notion of having an off-the-shelf solution. It's important to appreciate, you know, that every compliance plan is different. Things need to be customized. No two compliance plans should be the same. And there should be listening done by management about the need to focus on the particularities of a compliance plan, given the particular healthcare institution. And a good example of that not coming together, I think, is the recent Halifax Health case out of Florida, which I trust a lot of you have already heard about. The $85 million settlement that resulted because a compliance official who raised the issue about payments to physicians looking like they violated the Stark Act not really being listened to, resulting in a very significant settlement which, if it holds, will be among the largest we've seen in the industry. These are issues that can be best avoided by ensuring that your compliance officials are listened to. </p>
<p>It's a message that we at OIG always try to underscore whenever we have the opportunity to talk to management around the country in various sectors, both in writing and orally. It really is so significant a flaw for management when compliance officials are not listened to as they identify and say we have an issue, we need to mitigate it, we need to resolve it. An $85 million settlement which, as I say, if it holds, will be among the largest. We also need to adapt. The urban crow is a great adaptive creature. It actually will figure out that in order to get food it'll have a nut and it will actually place the nut in a crosswalk on a street so that cars will go over the nut and open it so that it can take advantage of it. And it will do so at times when there are red lights so that cars aren't coming down the street. It shows just incredible creativity in being able to make sure that it's actually able to eat what it's looking for. And I think the idea of being adaptable should be built into all of our practices and it's something that we at OIG try to practice ourselves. So when it comes, for example, to designing how to take care of compliance problems as they arise, we look, really, at a wide range of potential solutions. </p>
<p>You know, everything from exclusion, which doesn't allow, really, room to go forward into and to allow people to remain with our programs; to corporate integrity agreements that might run for a duration of three years or five years; to unilateral monitoring; to self-disclosure, institutions that are able to really take upon themselves these problems and resolve them effectively. Adaptability is absolutely crucial. Avoiding problems. I think that the upside-down turtle kind of is self-explanatory. It brings to mind, for me, a lot of adverse events issues and the need to pay attention to the problems of preventing harm. Our work has revealed that one -- 20 to 30 percent of the adverse events that occur in hospitals can be prevented. You know, we're talking about things basically like hand washing, to just ensuring that protocols are adhered to. So many mistakes are fully preventable. And a crucial role that you play is reminding the institution of that and helping to ensure that protocols are in place to avoid them. </p>
<p>One of the most tragic cases that have come across our desk at OIG concerns the Kwiatkowski case. This is one of the most tragic cases I've seen throughout my tenure. It concerned a medical technician who stole pain medication, injected himself with the pain medication, and replaced the vials with saline, thereby depriving patients of their pain medication and, at the same time, transmitting Hepatitis C. And dozens of patients around the country experienced harm, from the Rockies to New England. And the special agent in our office who helped break the case, who brought the matter to prosecution and conviction, she and I worked together on an Op Ed piece in the New York Times recently and I would encourage you to take a look at it. It's in the March 13th edition of the New York Times. </p>
<p>And there we make the plea for better safeguards, better controls. We know we can do a better job. And the notion of having that much harm occur repeatedly is something that really should not exist in an era like this where we have so many effective tools at our disposable. We can do so much better. We do so much better by taking, I think, an effective team approach to our work. I take the team approach idea to heart very much at OIG where we really work hard to bring together our different components. You know, we have scores of auditors and accountants around the country. We have many criminal investigators. We have many management analysts, evaluators, and we have a pretty large legal staff, as well. We work very hard to try to make us a coordinated team, to work together; because if we don't coordinate our work, we don't speak at one OIG. And it's so important, I think, for the compliance community, for the law enforcement community, for everybody we touch to understand that we have an integrated sense of our work. We know what we are trying to do as a group in attempting to prevent and detect fraud and abuse; and to promote economy, efficiency, and effectiveness in all of the HHS programs. And we need to do it together. And once we're on the same page internally as an organization, we need to be effective as a team with our external partners. </p>
<p>So we do make it a practice to reach out to our Federal law enforcement partners at the Department of Justice, U.S. Attorneys around the country. We do reach out to our Medicaid Fraud Control Units, to our state and local partners. We reach out within our department to CMS, which is charged with running the programs that are so important here. We are constantly looking at ways of being able to build an effective, coordinated team. We reach out to you to make sure that we operate a compliance regime that maximizes the opportunities to have the right things happen at the right time. It really does require thinking of what we do in a coordinated way, as a coordinated fashion. </p>
<p>Notwithstanding my talking about data being not quite as important as the biology of it, I do appreciate that we do live in a new and very exciting era of being able to obtain and navigate far more information to do our job effectively. With data, the new era of data, comes transparency and the need to secure that data more effectively. It has been said that, in an era in which data has now become really big, we're moving to mass application of individualized data and that's going to present a significant opportunity for us to deliver far more individualized care and, at the same time, run the risk that false assumptions will be made, anything from bad bias in sampling to not being able to understand what the data is telling us. There is a difference between data and information. We get tons of data, but do we get the valuable information that we need? That really requires human judgment, the kind of judgment that you're bringing to the table every day. We have a lot of new data. As a result, we can do a lot of new things. But we need to approach the subject with a real sense of why we need to handle that data in a discriminatory fashion. </p>
<p>We need to think about what is important and act on it and separate wheat from chaff. Here's the hawk. And I know that you'll be interested in what is coming down the pike from OIG this year. We're actually working, I think, on several very exciting initiatives, things that are very timely. Some might say overdue, but we've been working hard at them. I would put it into three categories: new safe harbors under the Anti-Kickback Statute; new authorities with respect to the Civil Monetary Penalties Law, our old 42 Part 1003; and exclusions, new authorities, updating the exclusions, including proposing early reinstatement provisions, which we haven't had before, trying to modernize our work in all three areas. I would say that as far as the new safe harbors and the new Civil Monetary Penalties Law provisions, those are still in process and are likely to have a longer timeline than our work on the exclusions, which I'm hoping that our new regs on exclusions will be available as early as later this spring or early summer. But those are all important new developments for OIG and we're hoping as a result of our work in these three areas that we will have a more updated, coherent, unified set of regulations and guidance that, in terms of their clarity, establishing how they fit together, will provide the compliance community and the legal community with a very valuable update of how our authorities are arrayed. </p>
<p>The eagle has great sight. And apparently it can see food from a mile away. I want to go back just a minute to the Halifax case. In Halifax, the compliance officer was really pleading with management to note what she viewed as serious Stark violations with respect to these contracts. And she was interviewed by Modern Healthcare magazine. If you haven't seen it yet, it's in the March 10th issue of Modern Healthcare. And she was asked about the settlement because she stands to receive a significant amount of money if the settlement holds. And it was interesting to me that what she said was, "I hope I can work again." She said, "I love this job." She said, "I love this job." And that really brought home to me how passionate compliance officers can be about their work. </p>
<p>And I would have ideally wanted the eagle to be kind of leaning in towards the seal because it struck me that what she was doing was that she was leaning in in her work. Now, that's an expression that has gotten some popular appeal lately because a very high executive, female executive, in the tech industry has written a book recently called Leaning In, in which she makes the case that women managers and executives should be more active in ensuring that they have an equal seat at the executive table with men. And I subscribe to that notion. As the father of two career daughters, I like the idea of women leaning in. But when it comes to the compliance industry, in terms of what we do, I subscribe to the notion that everybody in compliance should be leaning in and, indeed, that's what you do. </p>
<p>That's what I find exciting about coming to HCCA, is that when I talk to you in the halls, over a meal, during the cocktail receptions, I get the sense that you passionately feel that this is important work, and you are right. You are right. Because in your hands is the physical, mental, and financial health of the United States of America. It really is. The stakes for us don't get higher, because they affect so much of the vital interests of our country and, in some respects, of the world, given the role we play on the larger stage. So with that in mind, I just think it's tremendously important that, indeed, we do lean in. And the stories I hear about compliance officers doing exactly that is just inspiring. </p>
<p>And it makes me want to come back and share those stories with you as often as I possibly can. I want to end with the one slide that combines biology and technology. We've got both carbon and silicon on the screen here. We're constantly reaching out to make sure that you have what we're working on available to you. So please don't forget to be following us on Twitter, on YouTube, certainly on our website, with our podcasts. We devote a significant amount of time these days to packaging up vehicles of information and guidance so that we can have the biggest footprint possible in the compliance community to ease your work, to make it clearer, to have the authority set out in as coherent a fashion and be available for robust discussion and conversation whenever that can happen. </p>
<p>As always, it's such a great pleasure to be with you, and for me, the excitement only begins with you here in the morning. I'm really looking forward now to having a chance to say hello and engage in conversation throughout the week. Over the course of the years, I've been spending more and more time actually at the HCCA event like this, and I always find it, as I said, incredibly inspiring. So with that, thank you for your attention and best wishes for a great conference.</p>
<p>[ Applause ]</p>





<div class="contentSeparator"></div>

		
<p><p><a class="top" href="#top">Top</a></p></p>
<p><a class="back" href="/newsroom/podcasts/">Return to Podcasts</a></p>
					
				</div><!-- leftContentInterior ends -->
			</div>	<!-- leftSideInterior ends -->
			<div id="rightSide">
				<!--#include virtual="/layout/im-looking-for.asp" -->
				<!-- #include virtual="/layout/sub-navigation/subnavigation-media.asp" -->
				<!--#include virtual="/layout/exclusions-database.asp" -->
				<!--#include virtual="/layout/report-fraud.asp" -->
				<div class="clearPadding"></div>
				<!--#include virtual="/layout/email-alerts.asp" -->
			</div><!-- rightSide ends -->
			<div class="clear"></div>
		</div><!-- mainBody ends -->
	</div><!-- textReset ends -->
</div><!-- bodyContainer ends -->
<div id="footerContainer">
	<!--#include virtual="/layout/footer-top.asp" -->
</div><!-- footerContainer ends -->
<div id="footerBottomContainer">
	<!-- #include virtual="/layout/footer-bottom.asp" -->
</div><!-- footerBottomContainer -->
</body>
</html>
