
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<head>
<meta name="google-site-verification" content="tpATPqNEN3HXiSbtqevBE9NdgbuCiN9Vmr6EP94lx6w" />
<meta name="keywords" content="Video | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services" />
<meta name="description" content="Podcasts | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services" />
<title>Podcasts | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services</title>
<!--#include virtual="/layout/head.asp" -->



<!-------------/ head closes and body opens / --->

<!--#include virtual="/layout/head-body-tags.asp" -->

<!------------/ head closes and body opens / --->


<div id="bodyContainer">
	<div id="textReset">
	<!--#include virtual="/layout/header.asp" -->
			<div id="mainBody">
			<div id="leftSideInterior">
				<div id="breadcrumbs">
					<ul>
						<li>
							<a href="/">Home</a>
						</li>
						<li>
							<a href="/newsroom/index.asp">Newsroom</a>
						</li>
					
						<li>
						<a href="/newsroom/podcasts/">Podcasts</a>
						</li>
            
						<li>
						Transcript
						</li>            
            
					</ul>
				</div>
				<div id="leftContentInterior">
					<h1>Transcript for audio podcast: 2013 Health Care Compliance Association Compliance Institute Keynote Address</h1>

<p>From the Office of Inspector General of Department of Health and Human Services</p>

<p><a href="http://oig.hhs.gov">http://oig.hhs.gov</a></p>


<p>Thank you, Shawn. And thank you for those warm applause, and thank you HCCA for coming to the National Capital Area this year. As you may have heard, budgets are tight for the federal government and especially tough for those of us in the federal family to travel these days. So, it's very, very, helpful for, not just me but for others in our office and our federal partners to be able to come almost down the street and be able to join you. And I think it is so very, very important that there'll be a federal presence at HHCA as much as possible because everything that we're going to accomplish, we're going to accomplish together, and we can't do that from a distance, we need to have the ability to be able to join with you. So I'm especially happy to be with you here in our neck of the woods. Our first slide is a serene slide. And I'm following up a little bit on where we left things a year ago in Las Vegas when we talked about how stressful a healthcare compliance officer's job is. </p>
<p>We discussed that there has been some survey worked on rather recently that indicated that there are high levels of what I call negative stress, it's positive stress, the kind that makes you get up in the morning and want you to accomplish your job. We're talking about the kind of negative stress that occurs when you don't feel in control and off of your environment, and the people that you need to work with are not listening, are not an important part of the important objectives that you're trying to accomplish. And it was somewhat dispiriting to see that there are still surveys out there, they indicate that indeed stress  is great as it ever was in this field. And so, I wanted to at least start. After all, if you're going to spend your first 30 minutes of a Monday morning with the Inspector General I'm not quite sure that necessarily is the best way to have a stress for a day. [laughter] So at least I was going to start with a serene slide but it's more than that, we're going to make it something of a maritime theme this morning. </p>
<p>I said the National Capital Area a few minutes ago because we're not actually in Washington, DC, we're in Maryland. Maryland is a small state but it's not worthy in a couple of key respects. One is that, there's a lot of water, it's the home of the Chesapeake Bay. In fact, if you like crab cakes this is the place to have them. It is the home of the US Naval Academy up in Annapolis. And, if you can stay around the area for a while, the academy has a terrific exhibit right now on the bicentennial of the war of 1812, which was mostly a naval conflict. A lot of it occurred here in the state of Maryland. Next year, we'll actually be the bicentennial of the bombardment of Fort McHenry and the Star-Spangled Banner. </p>
<p>So, water is very important, small state with a very, very long coastline. Maryland also is a very prominent healthcare state. I mean, like other states it has major hospitals and research institutions, but it's also where key operations for the centers for Medicare and Medicaid services are located up in Baltimore, it's home of operations for the Food and Drug Administration, the National Institute of Health, is very much of a healthcare state. So, I wanted to combine our maritime theme here to take advantage of the fact that we're surrounded by water. And we're going to take a voyage this morning towards our objectives in the healthcare transformation that's occurring. We know that we're headed in the direction of a more efficient and effective healthcare system. And people have talked about the change in the landscape--the benefit of course of a landscape is that sometimes you have landmarks so you're better able to figure out where you're trying to go. When you're on the water, navigation becomes very, very key, and it's not necessarily obvious where you are. I mean this is a serene slide as long as you know where you are, but if you're in the middle of this water and you need to get somewhere and you don't have the tools this can actually be a very disturbing slide. </p>
<p>But I want you to think of our journey this morning as a voyage in a general direction towards getting greater efficiencies and effectiveness from our healthcare system, and that's going to focus on patient-centered care. This slide does not show any healthcare provider, it's actually a slide of a passenger-centered ship, one would hope. But I--what I'm doing here is taking advantage of the idea of a service that is directed towards those who are supposed to take advantage of that service for their benefit. So indeed--and this is the kind of metaphor that has been used very effectively by John Bogle, the founder and longtime chairman of the Vanguard family of mutual funds. John Bogle who always called his employees crew members, because he viewed it really as a voyage of discovery on how to get value out of investments. </p>
<p>In fact, if you've seen the Vanguard trademark, it's actually a picture of--during the 19th century battleship. And his view was the crew exists for the benefit of getting maximum value for the investors and the shareholders. The notion of this ship of course that's pictured is to make for as comfortable and safe--a ride for its passengers in the course of getting them to their destination. What we see in healthcare is that our healthcare enterprise is not very effective at being able to maximize value for those who get on the enterprise to take advantage of the services that are offered through our otherwise very, very impressive advance healthcare system. We don't want a ship that goes around in circles, that goes into dangerous waters, we need a healthcare enterprise that is directive, that's going in the right direction, that's doing so safely. And, it's so critical that we think in terms of a compliance function that helps make that possible. </p>
<p>The compliance function is going to change as a result of this more sophisticated thinking about getting a healthcare enterprise moving very definitively in the direction of greater efficiency and effectiveness. This is a significant change driven in large part by healthcare experts who found over the last 5 to 10 years that we can deliver healthcare and the savings of anywhere from 20 to 30 percent or more of current expenditures, healthcare system expends about 2.7 trillion dollars, our experts say that you can cut that by almost a third in many circumstances and still deliver the same care. So, that's a total order and it's not as if healthcare providers have not thought of themselves as patient-centered in the past, it's just that our knowledge of healthcare and medicine has moved on and technology now allows us to measure things that we couldn't measure before. So, we need to take advantage of these new findings, these new ways of doing business, and compliance is going to be a very critical part of it. Think in terms of a traditional treatment plan in which a compliance officer might have looked to see whether the plan is dated and signed. </p>
<p>Now, think in terms of a more clinical compliance operation where it would be important to look at the plan and see whether it has concrete, measurable, observable goals and objectives that actually served the needs of the person who's receiving the services, a more sophisticated exercise. And indeed, I do think the compliance function will be headed towards those kinds of more complicated functions. We need to chart that destination towards quality and cost effectiveness. And we have one person on the bridge, but it's going to take a whole team of people, we're going to need to think in a very cross disciplinary way. Perhaps we did so in the past to a certain degree, we need to double down on the idea that we really need to cross discipline far more effectively than we did in the past to make sure we're headed in the right direction. And that we do so keeping close account of the needs to always ensure passenger safety, patient safety, passenger quality, patient quality to get us to our destination. There are always vulnerabilities that we need to think about, that we need to have on our screen. This particular slide has accompanying slide which should reduce the stress that's caused by that slide. You know, it's April, and every April for a hundred years people will have occasion to see an iceberg, think about the Titanic. </p>
<p>Last year, you might remember was actually the centennial of the tragic sinking of the Titanic in April of 1912. The story is well known, 2,200 people were on the ship when it made its voyage from England to the United States. During the course of an evening about four or five nights in, the Titanic hit an iceberg over the course of an hour and a half it sunk. There were lifeboats on board but not enough to save anywhere near the full number of passengers out of the 2,200 that were on the ship about 700 has survived. At this point, after more than a hundred years you think there would be nothing new to say about the Titanic. </p>
<p>But actually, there are some late breaking news, and the news concerns safety officer, Morris Clark. The notebook of the safety officer who needed to certify that the ship was seaworthy just before sailing out of England, his notebooks became available just last fall and went up for auction in London, just this past November. And for the first time in a hundred years, we learned that Morris Clark, in deciding whether he could certify that the ship was sea worthy, he was a government employee, wrote in his notebook that he thought that the ship should have more lifeboats. He recommended that the ship have 50 percent greater capacity with lifeboats. It left England with 20, and most 20 lifeboats at least in theory should have been able to rescue about 1,100--about half of the 2,200 passengers. He recommended that there'll be 30 boats put on the ship. He's thinking and this was common at the time that because the sea lanes were rather well traveled, it will be a matter of trying to ferry people from one ship to another. But that if you had to ferry three times over with only 20 lifeboats, panic could ensue. So, he thought it was a good idea that more lifeboats be added. </p>
<p>But the White Star Line which run the Titanic apparently said, "No, no, no, no, no, no, no." And this was indicated in his notebook. He said, "I was fearful for my job. I received indications that this would not be possible." But what in a fact happened was White Star said, "How many lifeboats are necessary? What does the law require?" At the time, the law which dated back to the mid 1890's based on tonnage required 20 lifeboats. So White Star Line, in fact said to the safety officer, "We've meet the requirement of the law. We need to get going." And sure enough Morris Clark certifies the ship a seaworthy even though he knew that there weren't enough lifeboats. And then the inquiry that followed the sinking in all the testimony, he never indicated otherwise. </p>
<p>We've gone from more than a century with the close confidential notes of Morris Clark not available. And once can only imagine if there were more lifeboats and of course it wasn't handled especially well that night in theory a lot more people could have been saved, but certainly Morris Clark's failure to follow through on what he saw resulted in unnecessary deaths of hundreds of people. There's a story in there that I think is worth considering as we move towards boating up, reinforcing the complaints function and understanding that it's very difficult at times for the law to catch up with technological and other developments that occur. And it's very important to stay focused on quality, safety, the effectiveness. Irrespective of what any particular landmark law might require with any particular time. This is the one slide I have that shows a lot of ships. And I could spend the rest of our time together just talking about the importance of coordination. </p>
<p>Because so much of this evolving era has to do with creating a more coordinated care system across providers, decision groups, acute care, post-acute care institutions. I think of just how significant it is that we have an opportunity to have complaint officers from so many institutions getting together at this compliance institute. Sure to hear from speakers, but even more important to talk among yourselves, because cross provider compliance is the future of healthcare more and more. You don't necessarily see it right now in many corners of the country. I think it's estimated that various coordinated care models right now are in some form, perhaps in 10 percent of our healthcare environment, but the hand writing is on the wall. It's so important to be thinking across different providers. And everything that we do I think from a government perspective requires us to think about how important coordination is. </p>
<p>For example when it comes to the whole notion of accountable care organizations, and the notion of Medicare share its savings programs, bundled payment initiatives, all of those kinds of efforts to bring different providers together to provide manage and coordinated care for a certain population and beneficiaries, it's so important that we work together. And, if you look on our website at some of the proceedings that have occurred on exploring ACOs. You'll see documents not only from OIG but from CMS, from the IRS, from the Federal Trade Commission, the FTC, from the Justice Department. There are many pieces that are affected, many pieces of the law, in many parts of the healthcare landscape that are affected by this notion of a more coordinated effort. Within OIG itself of course, we put a premium on working with our partners in the federal community. </p>
<p>We talked about this in institutes passed that over the past several years, our office and our anti-fraud efforts, the so called HIT initiative have worked with CMS and with the justice department to shut down all kinds of fraud schemes whether it's infusion therapy or DME or home health. You know, significant criminal enterprises going on in some of the hot spots like South Florida, Houston, Los Angeles, and so forth. We can possibly get as much done as we have with our HIT initiative, if weren't working affectively hand in glove with our law enforcement partners. And, on the technological side it's very encouraging to see the kind of partnership that is now developing between the government and between private insurers through the healthcare fraud prevention partnership, which is effort underway this last year--year and a half to use data in a way that will allow us to identify common frauds schemes that exist both on the public and the private payer side. </p>
<p>This is something that was envisioned years ago in the HIPAA law of the mid 1990s but really only in the last several years have we really developed at this point the technological sophistication to protect data that needs to be protected either from a government or proprietary perspective, and be able to examine common coding issues, common ways of false billing that allow for a far more robust public-private exchange. So, coordinated care--and that's what all of these ships is about, is really designed to reemphasize if it needs it, that we really need to be working across disciplines, across agencies towards that common destination. I want to focus on some of the specific initiatives that we have at OIG. I think of our work really is trying to help direct industry towards making the most effective use on its resources so that we can move forward in the right direction. And, that's tugboat, I think of as the OIG tugboat trying to assist the larger healthcare enterprise. </p>
<p>The issue that comes to mind with this slide is our hospital compliance audits, which we've had in effect now since about 2010. We've looked at close to 80 hospitals. We've been able to recover about 34 million dollars over those years as a result of these audits, looking at common coding issues, transfers from acute to post-acute facilities, seeing where those issues are most common, and really being able to assist hospitals get this very important compliance issues right. With that and a lot of very positive feedback from a number of institutions that has really helped be able to refine their capacity. We expect to do another, about 25 over the course of the next year. </p>
<p>And, I do think that this way of doing business of being able to look across different lines of activity is something that has such value from a systemic standpoint that with technological advances we need to try to do the same in Part B services. So, without being able to get very specific with you now, I do hope that we'll be able to move to transfer a lot the benefits that we've seen with our hospital compliance we've used to that very large piece of the action called Part B and to be able to do some of kind of data mining that we think will be very helpful. New in just to last couple of weeks is OIG's updated Self-Disclosure Protocol. I have the slide here that shows a life preserver. I do think that this is really an initiative that's designed to help providers help themselves. </p>
<p>I can't emphasize enough how valuable it is to engage in self-policing. And we know as a community that the most common things that are likely to arise, false billing, kickback issues, employing excluded individuals. Those are the kinds of thing that most often result in possible fraudulent conduct. This needs to be identified, disclosed and resolved. We've been doing a self-disclosure protocol initiative now for a decade and a half, it goes back to 1998 and we're very committed as an office to continue to improve the process to make it more user-friendly. There's a terrific podcast actually on our website by Tony [inaudible] that kind of walks through how the STP works and can be most effectively utilized. I will encourage you to spend at least a few minutes with it. </p>
<p>I know there's been already some sessions devoted to and I actually found as I was coming in this morning hard copies of our self-disclosure protocol around our seats. So, I think there even extra copies of the hardcopy itself that just came out on April 17. I would encourage you to take a look at it, to be familiar with it. We have a lot of good informational materials about it on our website, take advantage of it. Keeping watch this slide is designed to emphasize that as supposed to throwing heat which we talked about a few minutes ago with respect to criminal enterprises, there's this so called pirate problem that we have in healthcare. We also try to throw light on the laws and the authorities that we have so that you have a full understanding of how OIG goes about overseeing the field and how you can be most effective in understanding what your responsibilities are. </p>
<p>So, again, look at the website to see our very helpful podcast and explanation of the False Claims Act of the Anti-Kickback Statute of what the Civil Monetary Penalties Law is about, of how exclusions work and in that respect, if you want a good sense of how the LEIE operates, I would encourage you to take a look at Andrea Berlin's podcast on our website. There's really good stuff on exclusions and there'll be more on it by the way shortly when we issue our special advisory bulletin that's expected and to issue soon. And, worthwhile material along with CMS on the Stark Law. </p>
<p>Our lighthouse is designed to throw lights so that there are no shipwrecks that we, you know, we avoid the problems that arise a result of sheer ignorance of the law, of not knowing what's required. Corporate integrity agreements, I emphasize self-disclosure protocols because to the extent that we can self-police effectively we find ourselves less involved in having to design corporate integrity agreements for those who have found themselves in very dangerous waters. Have got kind of beyond the boundaries and we need to assist in being able to channel behavior. Corporate integrity agreements have been around for a while now. </p>
<p>They have actually great potential to help provide us come out with model compliance programs and there's been feedback honestly from the pharmaceutical industry, from a skilled nursing facilities, about how working with CIAs have actually improved their operations and that they are very pleased, they're very happy with the ability to be able to follow a set of guidelines and directions that result in a far more robust and effective compliance environment. So, those bullies that you see are just a reminder that when necessary, there are corporate integrity agreements that as a result of settlements of cases will allow us to stay channeled and are very, very valuable. </p>
<p>This is a screen that shows sharks. Another recent OIG development is the publication of a Special Fraud Alert on physician owned distributorships, and this is an area where because of exposure under the Anti-Kickback Statute potentially for ambulatory surgery centers and hospitals, it would be extremely important to take advantage of our Special Fraud alert, read it with care, understand that Physician Owned Distributorships known as a PODs are inherently suspect and that because of the potential AKS liability for hospitals and for surgery centers it really is important to look very, very carefully whether these kinds of arrangements serve the healthcare provider or not. So, keep in mind the shark-infested waters. For years, I wanted to show what a safe harbor looks like.  </p>
<p>I don't know if this is a safe harbor or not. I hope it is for somebody or something. But this is a reminder that we have also issued very important publication on extending the current electronic health record safe harbor under the kickback statute. Right now what we publish back in 2006 is scheduled to expire at the end of the year, and really is a testament to how things, you know, take time, have evolved over the years that the original publication went back now seven, eight years. And now, we're at a somewhat different place but we're still looking to see how we can ensure that providers can receive that there could be a donation of electronic health records that will continue to promote interoperability that will move us slower on our national healthcare information technology platform and we want to make sure that we get these provisions right. </p>
<p>We want to make sure that we're recovering the right folks for the right reasons. So, please take a look, a close look at what has been published, comments are due by early June so we're still in the comment period but we're looking to extend the safe harbor. And safe harbor as you know are very, very important under the kickback statute and I think reveal a very, very important philosophy about trying to advance as much as possible, an effective, cooperative information technology environment for healthcare which brings me to data, technology, and electronic health records. Technology is really remarkable. I've heard it said that computers exist for the amplification of human intelligence and human capability. </p>
<p>Unfortunately, they also exist for the amplification of human error and sometimes human malice. So, we need to be very careful how we deal with technology that indeed, this is so much transforming our field. I have heard big data described by one academic as moving from the mass application of individual data to the individual application of mass information. We're really drilling down on the ability to take masses of information and be able to custom work, that kind of data in ways that were unimaginable in the 20th century. So, indeed, data, technology, and EHRs are very much in the future. I've got a I think a radar screen up there. It's a reminder that when it comes to maritime navigation it took quite a while to get it right. About the times that he Titanic sank, Sonar which stands for Sound Navigation and Ranging was just getting under way. Sonar was actually patented about a year after the Titanic sank. </p>
<p>So, we're talking about World War I. It took until about World War II, 1940 before Radar which is known Radiowave Detection and Ranging actually got up to 3531. So, we're talking about a significant time lag. Indeed, when it comes to data technology and EHRs, there are time lags as well. We need to be patient about the evolution of technology but impatient to apply it as quickly as possible and as effectively as possible and OIG along with other government partners are trying to work effectively with our private community to make sure that we do this as seamlessly as possible. It is a big job.</p>
<p> It is very important compliance job in large part. And compliance does check the direction that we're going. You play a critical part in all of this and I very, very much enjoy and appreciate the opportunity to come every year and talk to about how very, very valuable this is. Because I don't know whether anything I've said this morning is going to reduce anyone's stress. But these are the things I do know. I do know that you perform very important work. </p>
<p>You do it very well and you should be very proud of the work that you do. I do know that many of you exert heroic efforts as key members of your management team. You know, American healthcare like American law enforcement has not shortage of heroes, as we witness in action in Boston last week. American healthcare is innovative and it is very strong, and you and I are very fortunate to occupy position where we can make it stronger still. And with that, I leave you the maritime blessing and may you always enjoy fair seas, fair wind, and following seas. Thank you.</p>





<div class="contentSeparator"></div>

		
<p><p><a class="top" href="#top">Top</a></p></p>
<p><a class="back" href="/newsroom/podcasts/">Return to Podcasts</a></p>
					
				</div><!-- leftContentInterior ends -->
			</div>	<!-- leftSideInterior ends -->
			<div id="rightSide">
				<!--#include virtual="/layout/im-looking-for.asp" -->
				<!-- #include virtual="/layout/sub-navigation/subnavigation-media.asp" -->
				<!--#include virtual="/layout/exclusions-database.asp" -->
				<!--#include virtual="/layout/report-fraud.asp" -->
				<div class="clearPadding"></div>
				<!--#include virtual="/layout/email-alerts.asp" -->
			</div><!-- rightSide ends -->
			<div class="clear"></div>
		</div><!-- mainBody ends -->
	</div><!-- textReset ends -->
</div><!-- bodyContainer ends -->
<div id="footerContainer">
	<!--#include virtual="/layout/footer-top.asp" -->
</div><!-- footerContainer ends -->
<div id="footerBottomContainer">
	<!-- #include virtual="/layout/footer-bottom.asp" -->
</div><!-- footerBottomContainer -->
</body>
</html>
