
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<head>
<meta name="google-site-verification" content="tpATPqNEN3HXiSbtqevBE9NdgbuCiN9Vmr6EP94lx6w" />
<meta name="keywords" content="Video | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services" />
<meta name="description" content="Podcasts | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services" />
<title>Podcasts | Newsroom | Office of Inspector General | U.S. Department of Health and Human Services</title>
<!--#include virtual="/layout/head.asp" -->



<!-------------/ head closes and body opens / --->

<!--#include virtual="/layout/head-body-tags.asp" -->

<!------------/ head closes and body opens / --->


<div id="bodyContainer">
	<div id="textReset">
	<!--#include virtual="/layout/header.asp" -->
			<div id="mainBody">
			<div id="leftSideInterior">
				<div id="breadcrumbs">
					<ul>
						<li>
							<a href="/">Home</a>
						</li>
						<li>
							<a href="/newsroom/index.asp">Newsroom</a>
						</li>
					
						<li>
						<a href="/newsroom/podcasts/">Podcasts</a>
						</li>
            
						<li>
						Transcript
						</li>            
            
					</ul>
				</div>
				<div id="leftContentInterior">
					<h1>Transcript for audio podcast:
          <br />2015 Health Care Compliance Association Compliance Institute Keynote Address</h1>

<p>From the Office of Inspector General of Department of Health and Human Services</p>

<p><a href="http://oig.hhs.gov">http://oig.hhs.gov</a></p>


<p>[Gabe Imperato] Okay time to move onto our key note speaker which is Dan Levinson the Inspector General of the U.S. Department of Health and Human Services. Many of you know Dan has served since 2004 under four secretaries of the Department of Health and Human Services. The department is oversees all federal health programs, Medicare, Medicaid, Public Health, Mental Health Services, conducts audits, evaluations, and enforcement efforts in ensuring that these programs are maintained addressing fraud, abuse, and waste. I think you, those of you who have been here over the years have seen Dan speak before. </p>
<p>This is actually his 10th visit with us. Under Dan's leadership at the Office of Inspector General, it's efforts have expanded, personnel has expanded in the traditional efforts but I think all of you probably know and if don't I will tell you that the Office of Inspector General has taken a great leadership role with respect to compliance as not only a thought leader but in taking significant actions to promote the profession and to promote compliance in healthcare organizations. He's been very generous not only with his time but encouraging the participation of members of the Office of Council Office of Audit and Evaluations and Inspections from the Inspector General's Office which has meant a lot to HCCA over the years. With that, I'd like to introduce Dan so you can hear is remarks today.</p>
<p>[Dan Levinson] Good morning and thank you Gabe. Thank both Gabes this morning. I do want to note the extraordinary service that Semper Fi does. It's a very moving story and it got me thinking about the kinds of values that I find HCCA members have. The kind of support that you give to Semper Fi is extremely valuable. Obviously, it makes such a difference in the lives of our service men and they are out there on the frontlines defending the kinds of American values that we here at home try to promote in organizations like HCCA, so thank you for your support at Semper Fi. As Gabe mentioned, I've been here before. It's wonderful to join you for now the 10th year and I do want to thank Gabe as President of HCCA and his colleagues on the board for giving me this opportunity this year and in the years past, and thank Roy Snell the CEO of HCCA and the wonderful staff of folks who support his efforts to make sure that everybody is connected to our wider effort here. </p>
<p>We're going to talking about the road to compliance. I wanted to use the road as a theme because the road is kind of that horizontal notion of travel of moving forward, of having been somewhere, being somewhere now, and moving forward to somewhere in the future. We won't dwell on the past but I wanted note the past, take stock of the present, and think about what the future holds. This year actually marks the 50th anniversary of the Medicare and Medicaid programs. They were passed in 1965. At the time, Medicare was maybe a several billion dollar program covering Americans who had been born in the 19th century. Today, the nation spends more than a trillion dollars on the Medicare and Medicaid program covering more than one-third of our 320 million Americans. </p>
<p>It's gotten bigger, it's gotten more complex, and it's very different but when I think back to the mid-60s, not only was Medicare and Medicaid taking off but so was Silicone Valley; the whole notion of the computer chip, our economy was beginning to take a different shape than it had been before and there was a management consultant who actually passed away 10 years ago who at the time was talking about the emergence of the knowledge worker, Peter Drucker. Do you remember Peter Drucker? Yes, he not only deserves applause but he deserves to be read to this day because so many of his insights remain so timely and Peter Drucker talked about the knowledge worker. He said, "We were living in an age when manual labor on the assembly line was starting to shrink and there was in the emergence of the knowledge worker; who or what is a knowledge worker?" </p>
<p>And Drucker said, "A knowledge worker turns data into information." How do you convert data into information? Drucker said, "That a knowledge worker endows data with relevance and purpose and thereby, creates useful and productive information." And he emphasized that a knowledge worker was going to be a different kind of worker in America's workplace. Someone who by significant training, experience, education was going to be working with both heart and head, was going to be engaged, wanted to have meaningful work. </p>
<p>We're all knowledge workers here in the room. We very much personify what Peter Drucker was talking about and he was emphasizing how important it was for knowledge workers to feel that they were really making a difference. Knowledge workers by definition are specialized and here in the room we have an incredible range of specialists, people who vertically know the fields of audit, of the healthcare professions, nurses, social workers, physicians, human resources specialists, investigators, lawyers, across just an incredible wide range of specialties; vertical drilled deep down understandings of a field but what Drucker was also talking about was knowledge workers being able to elevate that knowledge to a wider understanding of the world to get that horizontal idea of working across different disciplines to make a difference for both their enterprise and for the wider community.</p>
<p>In effect, going from data to information to knowledge to the wisdom to be able to use that knowledge across all of the disciplines and of for that reason especially, I am very excited about posting on today's OIG website the new practical guidance for healthcare governing boards on compliance oversight. We have done this kind of product in the past with the help of HCCA. I'm especially excited about the notion that we have collaborated. OIG, HCCA had collaborated across disciplines with the American Health Lawyers Association with the Association of Healthcare Internal Auditors to come up with an extremely valuable document for you to share with your boards and you should be sharing it with your boards when you're at the table and, of course, you should be at the table with the boards in doing so. This document is going to cover many of the disciplines that we need to relate to and interact with in order to do the kind of job we know we need to do. So, we cover not just compliance but we do cover audit, we do cover legal, we do cover human resources and the quality function all of these aspects so very, very important. </p>
<p>We'll be talking about this more later but I want to emphasize that we will be dealing with the need to understand compliance in a world that continues to move, that continues to be very dynamic, certainly technologically and when I talk about technology I'm certainly talking about the continuing advances that we're making in electronic health records, in building out further interoperability, these are the kinds of terms that we didn't have to deal with the 20th century but technologically we have to be thinking about how we're going to navigate and manipulate data and with innovation, I think of the four Ps. </p>
<p>As some of you who have heard me talk before, I like the idea of coming up with acronyms and ways of being able to capture lists of vital information. Think about the four Ps that are more and more a part of our world; patient engagement, making sure that the patient comes first; payment delivery, we have new payment methods that are unfolding that we need to understand; performance measure, your performance is now becoming a critical part of the healthcare equation and the fourth P; program integrity, part and parcel of everything we need to be thinking about, and again, we need to be thinking about these things across the different disciplines. </p>
<p>As we go on the road to compliance, we need to think about what each different discipline faces. The healthcare professions themselves face important challenges in order to make this coordinated more accountable healthcare system of the future work. Just this week, as many of you know, congress passed and the President signed the Medicare Access and Children's Health Insurance Program Reauthorization Act of 2015. Along name but basically it was the Doc Fix Law that had created as you know an annual crisis when it comes to physician payments in the Medicare for nearly two decades. </p>
<p>The Doc Fix Law was passed but it wasn't simply the Doc Fix Law, there's a lot in that law that needs to understood and importantly there a lot of program integrity sections to the new law. There's a new take for example of the documentation requirements for DME under Medicare. Those are the kinds of things that you don't necessarily think about when you're thinking about the Doc Fix but there are important new provisions in this new law. It is a landmark piece of legislation. It was long overdue; it was wonderful to see the kind of bipartisan support it got. We need to drilldown and make sure we understand not just the Doc Fix itself but how these new merit-based incentive systems, the alternative payment models that are part of the new law, how they're really supposed to work and that's going to require the best compliance thinking not just in this room but, again, across the various disciplines because as the law was being passed one of the headlines in the New York Times was that physicians were pleased and they were anxious; pleased to see the old system go, very concerned about how new systems would unfold and what it meant for them. </p>
<p>So, it's an era in which the new is happening and the new if good but it's also creating a feeling of great concern and to certain degree of unsettlement about how it's going unfold. We need to keep heading on down the path of compliance in a way that brings everybody together. It's also a new era for business relationships. As we, again, continue to think in terms of coordinated and integrated care, we're going to be dealing with more providers, again, horizontally across different areas of our healthcare enterprise, so we need to know really who we're doing business with, you know, what of the potential referral relationships about. Do we know that our partners in business are professionally responsible? Financially responsible? Are they properly licensed? We now need to be thinking, again, more broadly about who our business partners are, they're relationship to us, how reimbursement is made and that requires, again, and important way of understanding in terms of billing, in terms of referrals what life is actually like when it comes to dealing with different business relationships. </p>
<p>As far as the law is concerned, obviously we live an environment in healthcare where it's vitally important to understand a variety of very, very important statutes, laws, rules, and regulations. I've talked in years past about coming up with a checklist of the laws that as compliance officers we need to feel familiar with. I use the acronym FACES, F for False Claims Act; A for the anti-kickback statute; C for the Civil Monetary Penalties Law, I see you're writing this down; E for the Exclusion Law and S for the so-called Stark Law the physician self-referral law that's named for the primary author of the law, FACES and to understand how those different laws work and the changes that are going on to understand what's going on with new Safe Harbors as a result of the technological innovations that have been going on over the last 10 years.</p>
<p>I can speak personally on this but we've come up with new Safe Harbors to try to encourage effective electronic health records and interoperability. We need to keep up-to-date with the various waivers of some healthcare fraud laws under some of the new experimental pay designs that are coming down the pike. These are all very, very significant changes. How do our friends over on the legal side of our enterprise, how did they address these issues? I can tell one thing, we know that they're very concerned about them. </p>
<p>This is my right pocket is my law pocket and I happen to have an article from the Wall Street Journal from just early February, "In-house lawyers worry about ethics, data, and trolls." This is reported by Ashby Jones. What's keeping the nation's top in-house lawyers up at night? At the top of the list this year, ethics and compliance according to the latest annual survey of general council and chief legal officers by the Association of Corporate Council, 96% of the lawyers surveyed said, "Ethics and compliance was important for 2015." And about one-quarter said the topic was "extremely important" a percentage that ranked higher than for all other categories. Not far behind ethics and compliance on the GC's list of concerns is a relative newcomer data breaches and protection of corporate data. More than a quarter of the GC's surveyed reported experiencing a data breach within the past two years a figure that hit a full 50% within the healthcare industry. </p>
<p>So, we know what our legal colleagues are concerned about. We need to be working with them, they need to be effective partners with us, again, one of the exciting aspects of the new board guidance is that we're bringing the health lawyers under the tent in with us on this guidance to help us look at this in a more comprehensive fashion. Accountability, because so much of the money that runs through our 3 trillion dollar healthcare system is public money it's so important that we understand that that money needs to be accounted for. </p>
<p>It's certainly something that we at HHS-OIG understand we have more auditors than any other professional occupation in our office, more than 600 internal auditors and CPAs are in HHS-OIG and I'm delighted that Gloria Jarmon, our deputy inspector general for audit, is here today and will be speaking at the conference expanding our knowledge our connections to the audit community is absolutely vital. They too face very, very important challenges and it's not just challenges on the public side where at HHS we need to be thinking about financial oversight of a trillion dollar HHS budget but it's also on the private side. </p>
<p>My left pocket is where I keep my audit articles and, again, from the Wall Street Journal I find that just a month or so ago there was an article as part of their falling CFO matters that some firms resist beefing up, companies hang on to outdated standards for safeguards designed to prevent errors and fraud. It so happens that the Treadway Commissions COSO standards that provide guidelines for internal audit, they've been revised. The standards that originally go back to 1992 were revised in 2013 and yet when the Wall Street Journal reporter looked at the reports coming down the pike a couple of months ago and saw that as of 20, end of 2014 there were scores of public companies that hadn't updated their internal audit guidelines to reflect the new COSO standards. </p>
<p>They noted that there seemed to be, you know, significant gaps in being able to at least stay current. The reporter noted that audit regulators have found flaws in nearly 40% of corporate audits done by the big four accounting firms in 2013 which was the last year they had records for. More than 180 companies disclosed material weaknesses in their internal controls in 2013, again, the latest year for which it's available. </p>
<p>So, an important connection was being made here in the press about making sure that when it comes to our audit standards that we stay current, that we stay modern and that many companies had yet to update them. We need to be working with the audit community, again, it's so helpful to have this kind of document where we're conveying to the board the importance of our different disciplines coming together to ensure compliance. We put it altogether and we realize that we need to be representative of this wider community, yes there are 7 elements of a good compliance program. People need to understand how those elements impact so many different aspects of the enterprise and it's up to us to promote that culture of compliance and fortunately, as I've said before to this audience, we have wonderful resources available at the click of a mouse if you still use one. </p>
<p>Certainly, the new guidance for governing boards which will be on our website as of today as part of our compliance 101 webpage an incredible amount of very, very valuable resources to be found, everything from Podcasts to the kind of basic instructional material that you will find very, very valuable. It will include the kind of drill down too, the U.S. Sentencing Commission guidelines of valuable conversation; important inside into the voluntary compliance program guidance that OIG has promoted across the various parts of the healthcare industry. </p>
<p>Again, a very, very important conversation about the corporate integrity agreements and you can go on our website and see that there are many CIAs with settling companies that will provide incredible detail to you on how to craft the best possible compliance program for your own enterprise, and of course, there's the work plan which we have issued every year which I know is something of a bible for compliance auditors because it gives you such a good firm sense of where the risk areas are, where the vulnerabilities are that we have found over the years that we have noted that we plan to addressing and it provides pretty very, very valuable roadmap. </p>
<p>Okay, so this is the present, and where are we headed? We're headed to thinking about quality care, quality care as opposed to what? Well, supposed to I guess quantity thinking not so much about simply the automatic delivery service but are we delivering quality care? Are we spending in a smart way? Is there unnecessary spending going, is the kind of spending going on really necessary for the kind of healthcare that's provided? Are we thinking in terms of wellness we're moving more towards a continuum of care as opposed to episodic, certainly there will always be a need for episodic care but we're now moving towards more of a health as opposed to a disease-based kind of system. This is the Triple Aim as its been called and that is the future, that is the future we need to imagine. </p>
<p>When we talk about imagining the future here at Disney World, this is the future that as healthcare professionals we need to imaging and we need to make a reality and this gives us our larger picture. This allows us to understand not only where we've been but we are and where we are going and how do we make this happen? Well, I began my talk this morning by referencing Peter Drucker a great management consultant who is no longer with us but let me refer to a very impressive management consultant who still is with us, William Ury maybe you've seen him on TED Talks or read his book "Getting to Yes." William Ury is a very thoughtful consultant who's talked about the importance of understanding that when you negotiate with somebody it's not just you and someone else on the other side of the table but there is a third presence always in the room. </p>
<p>It is the larger interests that are at stake and he encourages his clients to think about when they're at the table to mentally divide themselves to not just be at the table but to have part of themselves go up to the balcony and look over the entire room and understand the interests and the stakes that are really in play and for us as compliance professionals, when we're sitting with the board as we need to be doing, sitting with the board, it's not just us and it's not just the board, we're also in the balcony looking at we talked about the four Ps before; let me talk about the three Ps. There's always the provider, the patient, and the payer. It's a, there are larger interests that are permeating the room and that we need to be thinking about that. That's how we create the future. That in having the conversation with the board using all the resources that our practical guidance is going to provide we can be talking about the importance of serving making sure that we're serving the three Ps effectively, now how we do that? </p>
<p>We've talked about the problems of being able to connect well with board members. Certainly, bringing your substantive expertise is absolutely critical and that's why it's so valuable, I think, not only what happens in the breakout sessions here are HCCA but what happens in the hallway when you're networking and you're sharing stories, you're talking about the issues that you face and you're learning about the issues that you colleagues face and being able to exchange valuable information. But I think you also need to keep in mind the importance of your personal effort to just connect with people and I think that there was a very thoughtful piece done and as opposed to my legal pocket and my audit pocket I have a more personal pocket right up here near my heart where I keep social and leadership skills and it so happens that the report on Medicare compliance last December had as its lead. </p>
<p>Social leadership skills are as vital to chief compliance officer effectiveness as technical savvy and there was a lengthy article that talked about the importance of exercising personal skills in connecting with people. I was very impressed that Roy Snell actually was quoted in some length as your chief executive as emphasizing that, yes, it's important that people bring their expertise but it's also important that people bring their social savvy to the table as well. I was concerned that because it came out around holiday time, the issue is dated December 22nd, it might have been viewed as filler, you know as not that important but actually it's very important. It conveys a very significant message. </p>
<p>It's not just a technical expertise. It's being in the room and saying it is many ways it seems pleasant, this is really important. It's important for the health of the enterprise. We're in healthcare. Yes, we need to be thinking about the health of the provider, the payer, and the patient. The health of the provider depends in no small measure on what we do with our compliance program and it requires horizontally this appreciation for all of the disciplines that are represented in audit, in legal, in investigations. </p>
<p>It's a multidisciplinary exercise that's why I'm so excited about today's announcement that we have this new practical guidance for healthcare governing boards on compliance available. It's available for us, importantly it's available for our boards and I think it's going to make a huge difference I think in our ability to be able to relate to boards across the different disciplines. So, with that by all means take a look at the new document, understand all of its different aspects, bring it together for your board and by all means, stay in touch. Best of success. Thank you again as always.</p>





<div class="contentSeparator"></div>

		
<p><p><a class="top" href="#top">Top</a></p></p>
<p><a class="back" href="/newsroom/podcasts/">Return to Podcasts</a></p>
					
				</div><!-- leftContentInterior ends -->
			</div>	<!-- leftSideInterior ends -->
			<div id="rightSide">
				<!--#include virtual="/layout/im-looking-for.asp" -->
				<!-- #include virtual="/layout/sub-navigation/subnavigation-media.asp" -->
				<!--#include virtual="/layout/exclusions-database.asp" -->
				<!--#include virtual="/layout/report-fraud.asp" -->
				<div class="clearPadding"></div>
				<!--#include virtual="/layout/email-alerts.asp" -->
			</div><!-- rightSide ends -->
			<div class="clear"></div>
		</div><!-- mainBody ends -->
	</div><!-- textReset ends -->
</div><!-- bodyContainer ends -->
<div id="footerContainer">
	<!--#include virtual="/layout/footer-top.asp" -->
</div><!-- footerContainer ends -->
<div id="footerBottomContainer">
	<!-- #include virtual="/layout/footer-bottom.asp" -->
</div><!-- footerBottomContainer -->
</body>
</html>
