
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<head>
<meta name="google-site-verification" content="tpATPqNEN3HXiSbtqevBE9NdgbuCiN9Vmr6EP94lx6w" />
<meta name="keywords" content="Disclosure and Accounting of Protected Records by CMS Between 2006 and 2011 Report (OEI-09-11-00430) 01-31-2014" />
<meta name="description" content="Disclosure and Accounting of Protected Records by CMS Between 2006 and 2011 Report (OEI-09-11-00430) 01-31-2014" />
<title>Disclosure and Accounting of Protected Records by CMS Between 2006 and 2011 Report (OEI-09-11-00430) 01-31-2014</title>
<!--#include virtual="/layout/head.asp" -->

<!--===============  [ MOBILE MEDIA QUERIES ]  ===============-->
<!--#include virtual="/layout/mobile-queries.asp" -->
<!--===============  [ /MOBILE MEDIA QUERIES ]  ===============-->

<!-------------/ head closes and body opens, this frees us to add content outside the UI structure / --->

<!--#include virtual="/layout/head-body-tags.asp" -->

<!------------/ head closes and body opens / --->
<div id="bodyContainer" class="mobilized">

<!--===============  [ MOBILE BANNER ]  ===============-->
<!--#include virtual="/layout/mobile-banner.asp" -->
<!--===============  [ /MOBILE BANNER ]  ===============-->

	<div id="textReset">
	<!--#include virtual="/layout/header.asp" -->
			<div id="mainBody">
			<div id="leftSideInterior">


<div id="breadcrumbs" class="m-remove">
					<ul>
						<li>
							<a href="/">Home</a>
						</li>
						<li>
							<a href="/reports-and-publications/index.asp">Reports &amp; Publications</a>
						</li>
						<li>
							<a href="/reports-and-publications/oei/subject_index.asp">Office of Evaluation and Inspections</a>
						</li>
					
						<li>
							Report
						</li>
					</ul>
				</div>
        
<div id="leftContentInterior">

<div style="position:relative;">
<div class="twitter tweet-this">
<a data-text="Disclosure and Accounting of Protected Records by CMS Between 2006 and 2011" 
class="twitter-share-button" data-count="horizontal" data-via="oigathhs" href="https://twitter.com/share">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>        
</div> 
</div>



<h1>Report (OEI-09-11-00430)</h1>

<h2>01-31-2014<br />
Disclosure and Accounting of Protected Records by CMS Between 2006 and 2011</h2>

<h2 class="line">Complete Report</h2>

<p class="download">Download the 

<a href="/oei/reports/oei-09-11-00430.pdf" target="_blank">complete report</a>

<!-- Footer -->
<!--#include virtual="/layout/pdf_inline.asp" -->
</p>



<h2 class="line">Summary</h2>

<h3>WHY WE DID THIS STUDY </h3>
<p>CMS maintains millions of records containing financial and health-related information. Inappropriate disclosures of records or data maintained in a system of records (SOR) can result in loss of privacy or fraudulent activities.  The Privacy Act of 1974 (Privacy Act) governs Federal agencies' collection, use, and dissemination of individuals' records maintained in an SOR.  CMS maintains SORs, and its disclosures of records must be consistent with the Privacy Act.  Further, the Privacy Act requires CMS to implement safeguards that protect records maintained in an SOR and to account for any disclosures.  Among other things, CMS uses a data use agreement (DUA) to ensure its disclosures are in compliance with the Privacy Act.  A DUA is the legally binding agreement that contains the written terms and conditions that govern each disclosure.  Entities are required to submit a DUA and DUA-related documents to CMS prior to the disclosures.</p>

<h3>HOW WE DID THIS STUDY</h3>
<p>We reviewed data requests approved or renewed by CMS between September 2006 and August 2011.  We limited our review to approved data requests from health-related SORs.  We used the DUA tracking number generated by the Data Agreement and Data Shipping Tracking System (DADSS) to identify our population of approved requests.  We selected a simple random sample of 150 approved requests using the DUA tracking number.  We interviewed CMS staff and reviewed SOR notices, CMS policies, and documents in the user agreement files, i.e., the DUA and/or DUA-related documents.  We project our findings to our population.</p>

<h3>WHAT WE FOUND</h3>
<p>For at least 98 percent of all approved data requests in our sample, CMS's disclosures of records were consistent with the routine uses identified in the SOR notices.  Five percent of all data files disclosed by CMS were not requested in the DUAs or updated DUAs.  CMS did not have the DUAs on file for 33 percent of all user agreement files.  The absence of a DUA may limit CMS's ability to verify what data were requested.  For 29 percent of the user agreement files, CMS extended entities' use of data without documentation of requests for extensions.  Fifteen percent of DUAs were both expired and not closed properly by the entities.    </p>

<h3>WHAT WE RECOMMEND</h3>
<p>We recommend that CMS (1) develop a process to ensure that the data requested are the ones disclosed to the entity; (2) ensure that the DUA and DUA-related documents are in a user agreement file; (3) ensure that entities submit the required documents to properly close their DUAs; (4) use a standardized, documented process for requesting and approving DUA extensions; and (5) ensure that expiration dates are consistent between the DUA and DADSS.  CMS concurred with all five recommendations.  In its agency response, CMS stated that it was replacing DADSS with the Enterprise Privacy Policy Engine, an electronic information system designed to provide a 100-percent-traceable record of CMS's data disclosures.</p>


<p>Copies can also be obtained by contacting the Office of Public Affairs at <a href="mailto:Public.Affairs@oig.hhs.gov">Public.Affairs@oig.hhs.gov</a>.	</p>			
</div><!-- leftContentInterior -->
			</div>	<!-- leftSideInterior ends -->
			<div id="rightSide">
				<!--#include virtual="/layout/im-looking-for.asp" -->
				<!-- #include virtual="/layout/sub-navigation/subnavigation-reports-and-publications.asp" -->
				<!--#include virtual="/layout/exclusions-database.asp" -->
				<!--#include virtual="/layout/report-fraud.asp" -->
				<div class="clearPadding"></div>
				<!--#include virtual="/layout/email-alerts.asp" -->
			</div><!-- rightSide ends -->
			<div class="clear"></div>
		</div><!-- mainBody ends -->
	</div><!-- textReset ends -->
</div><!-- bodyContainer ends -->
<div id="footerContainer">
	<!--#include virtual="/layout/footer-top.asp" -->
</div><!-- footerContainer ends -->
<div id="footerBottomContainer">
	<!-- #include virtual="/layout/footer-bottom.asp" -->
</div><!-- footerBottomContainer -->
</body>
</html>

