
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<head>
<meta name="google-site-verification" content="tpATPqNEN3HXiSbtqevBE9NdgbuCiN9Vmr6EP94lx6w" />
<meta name="keywords" content="Office of Evaluation and Inspection, Reports, HHS, OIG" />
<meta name="description" content="Report" />
<title>Report &#124; Office of Evaluation and Inspection Services &#124; Reports &amp; Publications &#124; Office of Inspector General &#124; U.S. Department of Health and Human Services</title>
<!--#include virtual="/layout/head.asp" -->
<!-------------/ head closes and body opens, this frees us to add content outside the UI structure / --->

<!--#include virtual="/layout/head-body-tags.asp" -->

<!------------/ head closes and body opens / --->
<div id="bodyContainer">
	<div id="textReset">
	<!--#include virtual="/layout/header.asp" -->
			<div id="mainBody">
			<div id="leftSideInterior">


<div id="breadcrumbs">
					<ul>
						<li>
							<a href="/">Home</a>
						</li>
						<li>
							<a href="/reports-and-publications/index.asp">Reports &amp; Publications</a>
						</li>
						<li>
							<a href="/reports-and-publications/oei/subject_index.asp">Office of Evaluation and Inspection Services</a>
						</li>
					
						<li>
							Report
						</li>
					</ul>
				</div>
				<div id="leftContentInterior">



<h1><a name="begin_content"></a>Report  (OEI-03-10-00260)</h1>

<h2>08-17-2011<br />
Medicaid Brand-Name Drugs:  Rising Prices Are Offset by Manufacturer Rebates</h2>

<h2 class="line">Complete Report</h2>

<p class="download">Download the 

<a href="/oei/reports/oei-03-10-00260.pdf" target="_blank">complete report</a>

<!-- Footer -->
<!--#include virtual="/layout/pdf_inline.asp" -->
</p>



<h2 class="line">Summary</h2>


<p>Between 2005 and 2010, prices and payment amounts for Medicaid brand-name drugs increased at about three times the inflation rate.  However, these significant increases were offset by savings generated by the Medicaid drug rebate program.</p>
<p>According to a series of reports issued by AARP, wholesale acquisition costs (WAC) for the most widely used brand-name prescription drugs have risen significantly since 2002, substantially outpacing the inflation rate.  Senator Bill Nelson expressed concern over AARP's findings and requested that OIG review drug pricing changes and their impact on Government health care programs, such as Medicaid.  To address Senator Nelson's concerns, this study examined changes in WACs, average manufacturer prices (AMP), and Medicaid payment amounts for brand-name drugs between 2005 and 2010.  OIG additionally examined the effect of rebates paid by drug manufacturers as part of the rebate program.</p>
<p>Over the 5-year period under review, WACs, AMPs, and Medicaid payment amounts increased between 34 and 40 percent at the median while the inflation rate increased only 13 percent.  In addition to outpacing overall inflation, increases in prices and payment amounts for brand-name drugs outpaced the inflation rate in each of the 5 years under review.  However, we found that when the per-unit payment amounts for Medicaid brand-name drugs were adjusted to account for the rebate amounts paid to States by manufacturers, the per-unit net cost to Medicaid increased at a much lower rate than other points of comparison between 2005 and 2009 (rebate data were not available for 2010).  In fact, Medicaid's rebate-adjusted payment amounts for brand-name drugs actually declined at the median in 3 of 4 years, lagging behind the inflation rate.  </p>
<p>Taken as a whole, the results of our study indicate that price increases for brand-name drugs may not necessarily translate to corresponding increases in Medicaid costs.  Because of the savings generated by the rebate program, Medicaid's net costs for brand-name drugs actually increased at a lower rate than other points of comparison, including the inflation rate.  CMS reiterated these points in its comments, expressing its belief that the rebate program has been effective in helping to offset increasing Medicaid drug costs. </p>


				
</div><!-- leftContentInterior -->
			</div>	<!-- leftSideInterior ends -->
			<div id="rightSide">
				<!--#include virtual="/layout/im-looking-for.asp" -->
				<!-- #include virtual="/layout/sub-navigation/subnavigation-reports-and-publications.asp" -->
				<!--#include virtual="/layout/exclusions-database.asp" -->
				<!--#include virtual="/layout/report-fraud.asp" -->
				<div class="clearPadding"></div>
				<!--#include virtual="/layout/email-alerts.asp" -->
			</div><!-- rightSide ends -->
			<div class="clear"></div>
		</div><!-- mainBody ends -->
	</div><!-- textReset ends -->
</div><!-- bodyContainer ends -->
<div id="footerContainer">
	<!--#include virtual="/layout/footer-top.asp" -->
</div><!-- footerContainer ends -->
<div id="footerBottomContainer">
	<!-- #include virtual="/layout/footer-bottom.asp" -->
</div><!-- footerBottomContainer -->
</body>
</html>

